/**
 * Unified message types for cross-channel communication.
 *
 * All channel integrations (Discord, Telegram, etc.) normalize their
 * native message formats into these types before passing them to the gateway.
 */

/** Supported channel types */
export type ChannelType = 'discord' | 'console';

/** Attachment included with a message */
export interface Attachment {
  /** Original filename */
  name: string;
  /** MIME type (e.g. "image/png", "text/plain") */
  mimeType: string;
  /** URL or local path to the attachment */
  url: string;
  /** File size in bytes, if known */
  size?: number;
}

/**
 * Normalized inbound message from any channel.
 * Every channel adapter must convert its native format into this shape.
 */
export interface InboundMessage {
  /** Unique message ID (UUID, generated by Virgil) */
  id: string;
  /** Which channel this message came from */
  channel: ChannelType;
  /** Channel-native message ID (for replies, reactions, etc.) */
  channelMessageId: string;
  /** User identifier within the channel */
  userId: string;
  /** Display name of the sender */
  userName: string;
  /** Text content of the message */
  content: string;
  /** When the message was received */
  timestamp: Date;
  /** Thread or conversation group ID, if applicable */
  threadId?: string;
  /** ID of the message being replied to, if this is a reply */
  replyToId?: string;
  /** File attachments */
  attachments?: Attachment[];
}

/**
 * Response to send back through a channel.
 * The gateway produces these; channel adapters consume them.
 */
export interface OutboundMessage {
  /** Text content to send */
  content: string;
  /** Target channel */
  channel: ChannelType;
  /** Channel-native message ID to reply to */
  replyToId?: string;
  /** Thread ID to send within */
  threadId?: string;
}

/** Routing decision made by the router */
export type RouteTarget = 'ollama' | 'claude';

/**
 * Result of the router classifying a message.
 */
export interface RouteDecision {
  /** Which backend should handle this message */
  target: RouteTarget;
  /** Router's confidence in this decision (0–1) */
  confidence: number;
  /** Short explanation of why this route was chosen */
  reason: string;
}

/**
 * A stored conversation turn (user message + assistant response).
 */
export interface ConversationTurn {
  /** Turn number within the session */
  turnIndex: number;
  /** The user's message */
  userMessage: string;
  /** The assistant's response */
  assistantMessage: string;
  /** Which backend handled this turn */
  backend: RouteTarget;
  /** When this turn occurred */
  timestamp: Date;
}

/**
 * Session metadata for a conversation.
 */
export interface Session {
  /** Unique session ID */
  id: string;
  /** Channel this session belongs to */
  channel: ChannelType;
  /** User ID for this session */
  userId: string;
  /** Thread ID, if scoped to a thread */
  threadId?: string;
  /** When the session was created */
  createdAt: Date;
  /** When the session was last active */
  lastActiveAt: Date;
  /** Number of turns in this session */
  turnCount: number;
}
